[tox]
envlist = lint,typecheck,test
skipsdist = true

[testenv:lint]
deps =
    ruff
commands =
    ruff check custom_components/ tests/
    ruff format --check custom_components/ tests/

[testenv:typecheck]
deps =
    mypy
    homeassistant
    icmplib
commands =
    mypy custom_components/

[testenv:test]
deps =
    -r requirements_test.txt
commands =
    pytest {posargs}

[testenv:format]
deps =
    ruff
commands =
    ruff check --fix custom_components/ tests/
    ruff format custom_components/ tests/
